config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  resources :new_events, only: [:new, :create]
  resources :events, only: [:index, :show, :edit, :update, :destroy]

  # sessions
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  validates :start_at_date, presence: true

  def human_start_at_date
    "#{I18n.t('date.day_names')[start_at_date.days_to_week_start].capitalize} #{I18n.l start_at_date, format: :short}"
  end

  def human_start_at_time
    I18n.l start_at_time
  end

  def human_start_at
    if start_at_time
      "#{human_start_at_date} à #{human_start_at_time}"
    else
      human_start_at_date
    end
  end

  def google_map_address_link
    if address
      "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(address)}"
    else
      ""
    end
  end
end

app/models/new_event.rb
class NewEvent < ApplicationRecord

  self.table_name = "events"

  validates :title, presence: true
  validates :start_at_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::SecurePassword
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
    helper_method :current_user
    helper_method :user_signed_in?
    helper_method :user_super_admin?
  end

  def login(user)
    reset_session
    session[:current_user_id] = user.id
  end

  def logout
    reset_session
  end

  def redirect_if_authenticated
    redirect_to root_path, alert: "You are already logged in." if user_signed_in?
  end

  def user_signed_in?
    Current.user && Current.user.present?
  end

  def user_super_admin?
    user_signed_in? && Current.user.role == 'super_admin'
  end

  def current_user
    Current.user
  end

  private

  def set_current_user
    Current.user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :return_404_if_not_super_admin, only: [:edit, :new, :create, :delete]

  def index
    @today = Date.today
    @beginning_of_week = @today.at_beginning_of_week
    @end_of_week = @today.at_end_of_week
    @days_of_week = (@beginning_of_week..@end_of_week).to_a

    @ungrouped_events = Event
                          .where(start_at_date: @beginning_of_week..@end_of_week,
                                 deleted_at: nil,
                                 is_template: false,
                                )
                          .order(:start_at_date, :start_at_time)
    @events_by_date = @ungrouped_events.group_by(&:start_at_date)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.deleted_at = Time.now
    @event.save

    redirect_to root_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit('title',
                                  'description',
                                  'start_at_date',
                                  'start_at_hour',
                                  'start_at_minute',
                                  'location_name',
                                  'address')
  end


  def return_404_if_not_super_admin
    if ! user_super_admin?
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end
end

app/controllers/new_events_controller.rb
class NewEventsController < ApplicationController

  before_action :return_404_if_not_super_admin, only: [:new, :create]

  def new
    @start_at_time = params.has_key?(:start_at_time)
    @event = NewEvent.new()
  end

  def create
    start_at_date = Date.new(event_params["start_at_date(1i)"].to_i,
                             event_params["start_at_date(2i)"].to_i,
                             event_params["start_at_date(3i)"].to_i)
    hour = event_params['start_at_hour']
    minute = event_params['start_at_minute']
    start_at_time =
      if hour && minute
        "#{hour.to_i}:#{minute}"
      else
        nil
      end

    @event = NewEvent.new(title: event_params[:title],
                          description: event_params[:description],
                          is_template: event_params[:is_template],
                          start_at_date: start_at_date,
                          start_at_time: start_at_time,
                          location_name: event_params[:location_name],
                          address: event_params[:address],
                         )

    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:new_event).permit('title',
                                      'description',
                                      'start_at_date',
                                      'start_at_hour',
                                      'start_at_minute',
                                      'location_name',
                                      'address',
                                      'is_template')
  end


  def return_404_if_not_super_admin
    if ! user_super_admin?
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :redirect_if_authenticated, only: [:create, :new]

  def create
    # => debug
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user && @user.authenticate(params[:user][:password])
      login @user
      redirect_to root_path, notice: "Signed in."
    else
      flash.now[:alert] = "Incorrect email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Signed out."
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_new_edit_form.html.erb
<!-- form -->
<div class="p-6 mt-8">

  <%= form_with model: event do |form| %>

  <div class="mt-8">
    <!-- title input -->
    <div>
      <%= form.text_field :title, class: 'rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Titre*', required: true %>
      <% event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
  </div>

  <!-- description input -->
  <div class="mt-8">
    <%= form.text_area :description, class: 'flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 rounded-lg text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Description' %>
    <% event.errors.full_messages_for(:description).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <!-- start_at_date input -->
  <div class="mt-8">
    <label for="event_start_at_date_3i" class="text-gray-700">
      Date
    </label>
    <div class="flex gap-2">

      <!-- day -->
      <select id="event_start_at_date_3i" name="event[start_at_date(3i)]" class="rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent">
        <% current_day = Time.new.day %>
        <% number_of_days = Date.today.all_month.count %>
        <% (1..number_of_days).to_a.each do |day| %>
        <option value="<%= day %>" <%= 'selected=selected' if day == current_day %> >
          <%= day %>
        </option>
        <% end %>
      </select>

      <!-- month -->
      <select id="event_start_at_date_2i" name="event[start_at_date(2i)]" class="rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent">
        <option value="1">Janvier</option>
        <option value="2">Février</option>
        <option value="3">Mars</option>
        <option value="4">Avril</option>
        <option value="5">Mai</option>
        <option value="6">Juin</option>
        <option value="7" selected="selected">Juillet</option>
        <option value="8">Aout</option>
        <option value="9">Septembre</option>
        <option value="10">Octobre</option>
        <option value="11">Novembre</option>
        <option value="12">Decembre</option>
      </select>

      <!-- year -->
      <select id="event_start_at_date_1i" name="event[start_at_date(1i)]" class="rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent">
        <option value="2022" selected="selected">2022</option>
        <option value="2023">2023</option>
        <option value="2024">2024</option>
        <option value="2025">2025</option>
        <option value="2026">2026</option>
        <option value="2027">2027</option>
      </select>

      <% event.errors.full_messages_for(:start_at_date).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
  </div>

  <!-- start_at_time input -->
  <div class="mt-8">
    <div id="toggle_start_at_time">Activer un horaire</div><br>
    <div id="start_at_time_input" style="display:none">
      <select id="event[start_at_hour]">
        <option value="00">00</option>
        <option value="01">01</option>
        <option value="02">02</option>
        <option value="03">03</option>
        <option value="04">04</option>
        <option value="05">05</option>
        <option value="06">06</option>
        <option value="07">07</option>
        <option value="08">08</option>
        <option value="09">09</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
        <option value="15">15</option>
        <option value="16">16</option>
        <option value="17">17</option>
        <option value="18">18</option>
        <option value="19">19</option>
        <option value="20">20</option>
        <option value="21" selected="selected">21</option>
        <option value="22">22</option>
        <option value="23">23</option>
      </select>
      : <select id="event[start_at_minute]">
        <option value="00" selected="selected">00</option>
        <option value="15">15</option>
        <option value="30">30</option>
        <option value="45">45</option>
      </select>
    </div>
  </div>

  <!-- location name -->
  <div class="mt-8">
    <%= form.text_field :location_name, class: 'rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Nom du Lieu' %>
    <% event.errors.full_messages_for(:location_name).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <!-- address -->
  <div class="mt-8">
    <%= form.text_field :address, class: 'rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Adresse' %>
    <% event.errors.full_messages_for(:address).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <!-- submit -->
  <div class="flex w-full my-4">
    <%= form.submit value: submit_button_text, class: 'py-2 px-4  bg-purple-600 hover:bg-purple-700 focus:ring-purple-500 focus:ring-offset-purple-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg' %>
  </div>

  <% end %>

</div>

app/views/events/edit.html.erb
<div class="flex flex-col max-w-4xl items-center mx-auto h-auto">

  <div class="max-w-md px-4 py-8 bg-white rounded-lg shadow sm:px-6 md:px-8 lg:px-10">

    <!-- title -->
    <div class="self-center mb-2 text-xl font-light text-gray-800 sm:text-2xl dark:text-white">
      Modifier un évènement
    </div>

    <%= render partial: 'new_edit_form', locals: { event: @event, submit_button_text: 'Modifier' } %>
  </div>


</div>

<%= javascript_tag do %>

// toggle start at time
document.getElementById('toggle_start_at_time').onclick = function() {

  var hour   = document.getElementById('event[start_at_hour]');
  var minute = document.getElementById('event[start_at_minute]');
  var startAtTimeInput = document.getElementById('start_at_time_input');
  var toggleBtn = document.getElementById('toggle_start_at_time');

  if (hour.hasAttribute('name')) {
    hour.removeAttribute('name');
    minute.removeAttribute('name');
    startAtTimeInput.style.display = 'none';
    toggleBtn.innerHTML = "Activer un horaire";
  } else {
    hour.setAttribute('name', 'event[start_at_hour]');
    minute.setAttribute('name', 'event[start_at_minute]');
    startAtTimeInput.style.display = '';
    toggleBtn.innerHTML = "Désactiver l'horaire";
  }
};

<% end %>

app/views/events/index.html.erb
<div class="flex flex-col max-w-4xl items-center mx-auto h-auto">
  <% if user_super_admin? %>
    <h1> <%= link_to "New event", new_new_event_path %> </h1>
  <% end %>

  <div class="flex flex-col max-w-4xl mx-auto h-auto">
    <div class="space-y-2 pt-6 pb-8 md:space-y-5">
      <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14 text-center">Soirées à venir</h1>
      <p class="text-lg leading-7 text-gray-500 dark:text-gray-400 text-center px-2">Vos prochaines soirées et évènements à venir</p>
    </div>
  </div>

  <div class="w-full flex">

    <div class="mx-6 w-full flex flex-col ">

      <% @events_by_date.each do |start_at_date, events, index| %>

        <div class="flex flex-col mb-2">

          <!-- day of the week -->
          <div class="px-4 py-5 sm:px-6 w-full">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
              <%= t('date.day_names')[start_at_date.days_to_week_start].capitalize %> <%= l start_at_date, format: :short %>
            </h3>
          </div>

          <!-- event list -->
          <ul class="flex flex-col w-full border-gray-400 bg-white rounded-lg shadow">

            <% events.each do |event| %>

              <li class="flex flex-row w-full items-center p-4">

                <%= link_to event_path(event), class: 'grow' do %>
                  <div class="flex flex-row items-center">

                    <!-- thumbnails -->
                    <div class="w-10 h-10 mr-4">
                      <div class="block relative">
                        <%= image_tag(event.image, class: "mx-auto object-cover rounded-full h-10 w-10") if event.image %>
                      </div>
                    </div>

                    <div class="flex flex-col">

                      <!-- title -->
                      <div class="font-medium">
                        <%= event.title %>
                      </div>

                      <!-- start at time -->
                      <% if event.start_at_time %>
                        <div class="text-gray-600 text-xs">
                          <%= event.human_start_at_time %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>

                <div class="flex shrink items-center">
                  <% if user_super_admin? %>

                  <!-- edit -->
                    <a href="<%= edit_event_path(event) %>">
                      <svg xmlns="http://www.w3.org/2000/svg" height="20" width="20" class="hover:text-gray-800 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                      </svg>
                    </a>

                    <!-- delete -->
                    <a href="<%= event_path(event) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure?">
                      <svg xmlns="http://www.w3.org/2000/svg" height="20" width="20" class="hover:text-gray-800 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                     </svg>
                    </a>
                  <% end %>

                  <!-- button show more -->
                  <%= link_to event_path(event) do %>
                    <svg fill="currentColor" height="20" width="20" class="hover:text-gray-800 text-gray-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                      <path d="M1363 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45l166-166q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z">
                      </path>
                    </svg>
                  <% end %>

                </div>
              </li>

            <% end %>

          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% if user_super_admin? %>
  <li><%= link_to "Edit", edit_event_path(@event) %></li>
  <li><%= link_to "Destroy", event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

<!-- MENU -->
<div class="flex max-w-4xl items-center mx-auto">
  <a class="font-medium text-gray-900 mx-auto block" href="/events">Soirées</a>
</div>

<div class="bg-white overflow-hidden">

  <div class="relative max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
    <div class="hidden lg:block bg-gray-50 absolute top-0 bottom-0 left-3/4 w-screen"></div>
    <div class="mx-auto text-base max-w-prose lg:grid lg:grid-cols-2 lg:gap-8 lg:max-w-none">
      <div>

        <!-- date + time -->
        <figcaption class="mt-3 flex text-sm text-gray-500">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" color="rgb(79 70 229)" stroke="currentColor"
               stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0
                                                                    00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <h2 class="ml-2 text-base text-indigo-600 font-semibold tracking-wide">
            <%= @event.human_start_at %>
          </h2>
        </figcaption>

        <!-- title -->
        <h3 class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
          <%= @event.title %>
        </h3>

      </div>
    </div>
    <div class="mt-8 lg:grid lg:grid-cols-2 lg:gap-8">
      <div class="relative lg:row-start-1 lg:col-start-2">
        <svg class="hidden lg:block absolute top-0 right-0 -mt-20 -mr-20" width="404" height="384" fill="none" viewBox="0 0 404 384" aria-hidden="true">
          <defs>
            <pattern id="de316486-4a29-4312-bdfc-fbce2132a2c1" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
              <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="404" height="384" fill="url(#de316486-4a29-4312-bdfc-fbce2132a2c1)" />
        </svg>
        <div class="relative text-base mx-auto max-w-prose lg:max-w-none">
          <figure>

            <!-- image -->
            <div class="aspect-w-12 aspect-h-7 lg:aspect-none">
              <%= image_tag(@event.image, width: 1184, height: 1376, class: "rounded-lg shadow-lg object-cover object-center") if @event.image %>
            </div>

          </figure>
        </div>
      </div>

      <div class="mt-8 lg:mt-0">

        <!-- location & address  -->
        <% if @event.location_name %>
          <div class="text-base max-w-prose mx-auto lg:max-w-none">

            <!-- location -->
            <p class="text-lg text-gray-500"><%= @event.location_name %></p>

            <!-- address -->
            <% if @event.address %>
              <figcaption class="mt-3 flex text-sm text-gray-500">
                <!-- Heroicon name: location-address -->
                <svg class="flex-none w-6 h-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                <a class="ml-2 underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="<%= @event.google_map_address_link %>">
                  <%= @event.address %>
                </a>
              </figcaption>
            <% end %>
          </div>
        <% end %>

        <!-- description -->
        <div class="mt-5 prose prose-indigo text-gray-500 mx-auto lg:max-w-none lg:row-start-1 lg:col-start-1">
          <% @event.description.split("\n").each do |description| %>
            <%= description %> <br>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetMe.Dance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!-- logout link -->
  <% if user_signed_in? %>
    <%= link_to "Logout", logout_path, method: "DELETE", data: {"turbo-method": "DELETE"}%>
  <% end %>

  <body class="w-screen h-screen">

      <!-- HEADER -->
      <header class="max-w-4xl mx-auto pt-5 grid place-items-center md:py-5">
        <!-- LOGO -->
        <a class="h-full" href="/">
          <%= image_tag('logo.png', class: "mx-auto md:m-0 h-40") %>
        </a>
      </header>

    <%= yield %>
  </body>
</html>

app/views/new_events/new.html.erb
<div class="flex flex-col max-w-4xl items-center mx-auto h-auto">

  <div class="max-w-md px-4 py-8 bg-white rounded-lg shadow sm:px-6 md:px-8 lg:px-10">

    <!-- title -->
    <div class="self-center mb-2 text-xl font-light text-gray-800 sm:text-2xl dark:text-white">
      Créer un évènement
    </div>

    <h1> <%= link_to "New event with time", new_new_event_path(start_at_time: true) %> </h1>
    <h1> <%= link_to "New event without time", new_new_event_path %> </h1>

    <%= render partial: 'new_edit_form', locals: {
        event: @event,
        start_at_time: @start_at_time,
        create_button_text: 'Créer',
        } %>
  </div>
</div>